const defaults=[
{name:'Push Ups',muscle:'Chest · Shoulders · Triceps',category:'Strength',kcal:70,img:'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=600&q=80'},
{name:'Squats',muscle:'Legs · Glutes',category:'Strength',kcal:95,img:'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=600&q=80'},
{name:'Deadlifts',muscle:'Back · Legs',category:'Strength',kcal:110,img:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=600&q=80'},
{name:'Bench Press',muscle:'Chest · Triceps',category:'Strength',kcal:100,img:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80'},
{name:'Plank',muscle:'Core',category:'Core',kcal:45,img:'https://images.unsplash.com/photo-1600881333168-2ef49b341f30?auto=format&fit=crop&w=600&q=80'},
{name:'Running',muscle:'Cardio · Legs',category:'Cardio',kcal:180,img:'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=600&q=80'},
{name:'Bicep Curls',muscle:'Biceps · Arms',category:'Strength',kcal:55,img:'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=600&q=80'},
{name:'Lunges',muscle:'Legs · Glutes',category:'Strength',kcal:85,img:'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=600&q=80'}
];
let state=JSON.parse(localStorage.getItem('fittrack-premium')||'null')||{exercises:defaults,meals:[{name:'Breakfast',kcal:420,protein:25,carbs:45,fat:14},{name:'Lunch',kcal:520,protein:35,carbs:60,fat:18},{name:'Dinner',kcal:310,protein:25,carbs:15,fat:13}],burned:423,streak:5,gender:'male',planDays:[0,1,2,3,4]};
function save(){localStorage.setItem('fittrack-premium',JSON.stringify(state))}
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});renderAll()}
function renderExercises(list=state.exercises){const el=document.getElementById('exerciseList');if(!el)return;el.innerHTML=list.map((e,i)=>{const ix=state.exercises.indexOf(e);return '<article class="exercise" onclick="exerciseDetail('+ix+')"><div class="exercise-img" style="background-image:url(\''+e.img+'\')"></div><span class="tag2">'+e.category+'</span><div class="exercise-info"><b>'+e.name+'</b><small>'+e.muscle+'</small><small>🔥 ~'+e.kcal+' kcal</small></div></article>'}).join('');document.getElementById('exerciseCount').textContent=state.exercises.length}
let activeFilter='All';
function filterExercises(){const q=(document.getElementById('exerciseSearch')?.value||'').toLowerCase();renderExercises(state.exercises.filter(e=>(activeFilter==='All'||e.category===activeFilter||(activeFilter==='Custom'&&e.custom))&&(e.name+' '+e.muscle).toLowerCase().includes(q)))}
function setupExerciseChips(){document.querySelectorAll('#exerciseChips .chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('#exerciseChips .chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;filterExercises()})}
function openModal(html){document.getElementById('modalCard').innerHTML=html;document.getElementById('modal').classList.add('show')}
function closeModal(){document.getElementById('modal').classList.remove('show')}
function closeModalOnBackdrop(e){if(e.target.id==='modal')closeModal()}
function openExerciseModal(){openModal('<h2>Create exercise</h2><label>Exercise name<input id="exName" placeholder="e.g. Incline dumbbell press"></label><label>Muscles trained<input id="exMuscle" placeholder="Chest · Shoulders"></label><label>Category<select id="exCategory"><option>Strength</option><option>Cardio</option><option>Core</option></select></label><label>Estimated calories burned<input id="exKcal" type="number" value="80"></label><label>Exercise image URL (optional)<input id="exImg" placeholder="Paste an image URL"></label><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" style="margin:0" onclick="addExercise()">Add exercise</button></div>')}
function addExercise(){const name=document.getElementById('exName').value.trim(),muscle=document.getElementById('exMuscle').value.trim();if(!name||!muscle){alert('Please add an exercise name and muscles trained.');return}const img=document.getElementById('exImg').value.trim()||'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=600&q=80';state.exercises.push({name,muscle,category:document.getElementById('exCategory').value,kcal:Number(document.getElementById('exKcal').value)||0,img,custom:true});save();closeModal();renderAll();showScreen('workout')}
function exerciseDetail(i){const e=state.exercises[i];openModal('<div class="exercise-img" style="height:190px;border-radius:16px;background-image:url(\''+e.img+'\')"></div><h2 style="margin-bottom:4px">'+e.name+'</h2><p style="color:#9aa5a1">'+e.muscle+'</p><p>Estimated burn: <b style="color:#48f09a">~'+e.kcal+' kcal</b></p><div class="modal-actions"><button class="secondary" onclick="closeModal()">Close</button><button class="primary" style="margin:0" onclick="logExercise('+i+')">Complete workout ✓</button></div>')}
function logExercise(i){state.burned+=state.exercises[i].kcal;save();closeModal();renderAll();alert(state.exercises[i].name+' logged! +'+state.exercises[i].kcal+' kcal burned.')}
function foodTotals(){return state.meals.reduce((a,m)=>({kcal:a.kcal+m.kcal,protein:a.protein+m.protein,carbs:a.carbs+m.carbs,fat:a.fat+m.fat}),{kcal:0,protein:0,carbs:0,fat:0})}
function renderMeals(){const t=foodTotals(),left=Math.max(0,2500-t.kcal),pct=Math.min(100,Math.round(t.kcal/25));const list=document.getElementById('mealList');if(list)list.innerHTML=state.meals.map((m,i)=>'<div class="meal"><div><b>🍽️ '+m.name+'</b><small style="display:block;color:#77837f;margin-top:4px">P '+m.protein+'g · C '+m.carbs+'g · F '+m.fat+'g</small></div><div><span>'+m.kcal+' kcal</span></div></div>').join('');['foodTotal','foodHome'].forEach(id=>{const x=document.getElementById(id);if(x)x.textContent=id==='foodHome'?t.kcal.toLocaleString():t.kcal});const leftEl=document.getElementById('foodLeft');if(leftEl)leftEl.textContent=left+' left';const rem=document.getElementById('remainingFood');if(rem)rem.textContent=left+' left';const per=document.getElementById('foodPercent');if(per)per.textContent=pct+'%';document.querySelectorAll('.calorie-donut').forEach(x=>x.style.background='conic-gradient(var(--green) '+pct+'%,#1a2524 0)');document.querySelectorAll('.big-ring').forEach(x=>x.style.background='radial-gradient(circle,#0d1417 59%,transparent 60%),conic-gradient(var(--green) '+pct+'%,#192423 0)');const vals=[['proteinValue',t.protein],['carbValue',t.carbs],['fatValue',t.fat]];vals.forEach(([id,v])=>{const x=document.getElementById(id);if(x)x.textContent=v+'g'})}
function openFoodModal(){openModal('<h2>Add food</h2><label>Food name<input id="foodName" placeholder="e.g. Chicken rice bowl"></label><label>Calories<input id="foodKcal" type="number" placeholder="450"></label><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px"><label>Protein g<input id="foodP" type="number" value="0"></label><label>Carbs g<input id="foodC" type="number" value="0"></label><label>Fat g<input id="foodF" type="number" value="0"></label></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" style="margin:0" onclick="addFood()">Add food</button></div>')}
function addFood(){const name=document.getElementById('foodName').value.trim(),kcal=Number(document.getElementById('foodKcal').value);if(!name||!kcal){alert('Add a food name and calories.');return}state.meals.push({name,kcal,protein:Number(document.getElementById('foodP').value)||0,carbs:Number(document.getElementById('foodC').value)||0,fat:Number(document.getElementById('foodF').value)||0});save();closeModal();renderAll()}
function calculateBMR(){const age=+document.getElementById('age').value||25,w=+document.getElementById('weight').value||70,h=+document.getElementById('height').value||175;const bmr=Math.round(10*w+6.25*h-5*age+(state.gender==='male'?5:-161));document.getElementById('bmrResult').textContent=bmr.toLocaleString()+' calories/day'}
function setupSelectable(){document.querySelectorAll('.selectable').forEach(group=>group.querySelectorAll('button').forEach(btn=>btn.onclick=()=>{group.querySelectorAll('button').forEach(x=>x.classList.remove('active'));btn.classList.add('active')}));document.querySelectorAll('#goals button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('#goals button').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')});document.querySelectorAll('#gender button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('#gender button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.gender=btn.dataset.gender;save();calculateBMR()})}
function setupDays(){const el=document.getElementById('days');if(!el)return;const names=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];el.innerHTML=names.map((d,i)=>'<button class="'+(state.planDays.includes(i)?'on':'')+'" data-day="'+i+'">'+d+'</button>').join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.day);b.classList.toggle('on');state.planDays=Array.from(el.querySelectorAll('.on')).map(x=>Number(x.dataset.day));save()})}
function savePlan(){save();alert('Your training plan is saved! '+state.planDays.length+' training days selected.');showScreen('home')}
function renderProgress(){const muscles=[['Chest',80],['Back',70],['Shoulders',65],['Arms',60],['Legs',75],['Core',50]];const m=document.getElementById('muscles');if(m)m.innerHTML=muscles.map(x=>'<div class="muscle-row"><div><span>'+x[0]+'</span><b>'+x[1]+'%</b></div><i style="width:'+x[1]+'%"></i></div>').join('');const hm=document.getElementById('homeMuscles');if(hm)hm.innerHTML=muscles.slice(0,4).map(x=>'<div class="muscle-mini"><span>'+x[0]+'</span><b style="color:var(--green)">'+x[1]+'%</b></div>').join('');const vals=[40,75,52,82,58,76,63],names=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];const bars=document.getElementById('bars');if(bars)bars.innerHTML=vals.map((v,i)=>'<div class="bar" style="height:'+v+'%"><small>'+names[i]+'</small></div>').join('');const bh=document.getElementById('burnedHome');if(bh)bh.textContent=state.burned;const bp=document.getElementById('burnedProgress');if(bp)bp.textContent=state.burned+' kcal today';const st=document.getElementById('streakHome');if(st)st.textContent=state.streak}
function renderAll(){renderExercises();renderMeals();renderProgress();setupSelectable();setupDays();setupExerciseChips()}
renderAll();